```{r setup, include=FALSE}
WORDS_TO_IGNORE <- c("médio-pied", "running", "supinatrice")
source("knitr-options.R")
source("spelling-check.R")
```

# Choisir ses chaussures de running {-}

Bien choisir ses chaussures de running est essentiel pour améliorer ses performances,
prévenir les blessures et optimiser son confort. Voici les principaux critères à prendre en compte pour
sélectionner une paire adaptée à vos besoins et à votre morphologie.
Si des douleurs se manifestent, il peut être aussi bénéfique d'aller voir un podologue pour faire des semelles orthopédiques.

## Déterminer son type de foulée {-}

Il existe trois types de foulée principaux, chacun influençant l'usure et le type de soutien nécessaire :

- **Pronatrice** : lorsque le pied roule vers l'intérieur à l'impact.
Une chaussure avec un soutien accru sur le côté intérieur peut être recommandée.

- **Supinatrice** : lorsque le pied roule vers l'extérieur.
Les supinateurs devraient rechercher des chaussures offrant une meilleure absorption des chocs.

- **Neutre** : lorsque le pied reste aligné sans roulement excessif.
Un grand choix de chaussures neutres est disponible, permettant de choisir en fonction du confort.

Pour déterminer votre type de foulée, vous pouvez observer l'usure de vos anciennes chaussures
ou consulter un spécialiste en magasin.

## Choisir le drop en fonction de sa foulée et de son expérience {-}

Le **drop** correspond à la différence de hauteur entre le talon et l'avant-pied.
Voici quelques repères pour bien choisir :

- **Drop élevé (8-12 mm)** : recommandé pour les coureurs débutants ou ceux qui attaquent le sol par le talon.
Ce type de drop aide à réduire l'impact au niveau des mollets et du tendon d'Achille.

- **Drop moyen (4-8 mm)** : convient aux coureurs intermédiaires ou aux coureurs polyvalents,
cherchant un équilibre entre attaque talon et médio-pied.

- **Faible drop (0-4 mm)** : favorise une foulée avant-pied et convient surtout aux coureurs expérimentés
habitués aux faibles drops. À utiliser progressivement pour éviter les blessures.

## Choisir le bon amorti en fonction de la distance et du terrain {-}

Les besoins en amorti dépendent de la distance parcourue, de la fréquence d'entraînement, et des surfaces courues :

- **Courses sur route** : privilégier un bon amorti, surtout pour les longues distances où
l'impact répétitif peut être éprouvant pour les articulations.

- **Courses sur piste** : un amorti léger suffit, avec un poids réduit pour améliorer la vitesse.

- **Trail** : un amorti adapté et une semelle crantée pour assurer l'adhérence sur terrain accidenté
et absorber les impacts sur les descentes et montées techniques.

## La taille et le confort de la chaussure {-}

Prendre une demi-pointure au-dessus de votre pointure habituelle peut être utile pour éviter
les frottements et laisser de l'espace au pied lors des gonflements pendant les sorties longues.
Veillez à ce que vos orteils aient de la place pour bouger, sans glisser.

Enfin, testez vos chaussures en fin de journée, lorsque vos pieds sont plus gonflés,
pour vous assurer d'un confort optimal pendant vos courses.
