```{r setup, include=FALSE}
WORDS_TO_IGNORE <- c(
  "And", "Bend", "Breakdancer", "Butterfly", "Cat", "Cow", "Dog", "Downward", 
  "Facing", "Forward", "GOWOD", "Hamstring", "Hamstrings", "Hip", "Piriformis", 
  "Prayer", "Quad", "Rack", "Sagittarius", "Sit", "Supine", "The", "Turtle", "Wall")
source("knitr-options.R")
source("spelling-check.R")
```

# La gestion de l'entraînement {-}

Gérer son entraînement est essentiel pour progresser tout en évitant le surentraînement et les blessures.
Voici quelques concepts clés à prendre en compte :

## L'échauffement et les étirements {-}

L'échauffement est essentiel pour préparer les muscles à l'effort et réduire les risques de blessures. Pour cela, rien de mieux que de trottiner 15-20 minutes lentement. 

Les étirements dynamiques (comme les montées de genoux et talons-fesses) permettent d'échauffer les muscles et les articulations avant une activité physique. Ils augmentent la circulation sanguine, activent le système nerveux, et préparent le corps à l'effort en améliorant l'amplitude de mouvement.

**Améliorer sa mobilité par des étirements réduit les contraintes mécaniques qui freinent la foulée, tout en diminuant le risque de blessures et en optimisant l'efficacité de la course.**
Les étirements passifs sont souvent pratiqués dans une optique de détente et d'amélioration de la souplesse. Cependant, ils ne sont pas recommandés juste avant une activité physique intense, car ils peuvent temporairement réduire la force musculaire et la réactivité.
De même, ils sont à éviter immédiatement après une séance éprouvante (type fractionné, musculation ou course longue), moment où les muscles sont encore fragilisés par l'effort : cela pourrait accroître le risque de lésions musculaires.
Il est donc préférable de réserver les étirements passifs à distance des séances, par exemple lors de journées de repos ou à l'issue d'un échauffement léger, pour travailler la mobilité et la souplesse sans interférer avec la récupération.
Je les pratique le midi, sachant que je cours plutôt le soir.

### L'application GOWOD {-}

J'ai découvert une application vraiment bien faite pour améliorer sa mobilité : GOWOD. Dans sa version gratuite, GOWOD offre plus de 300 exercices illustrés par des vidéos et des explications, ainsi qu'un premier test de mobilité avec résultats personnalisés à son sport (ou plusieurs) pour guider l'amélioration de la souplesse et de la performance.

Ce que je vous propose :

- Installer l'application GOWOD et faire le premier test de mobilité gratuit, en précisant que votre sport principal est la course à pied, pour prendre conscience des parties du corps à travailler en priorité. J'ai l'impression que pour la plupart des coureurs, c'est la mobilité de toute la chaîne postérieure qui fait le plus défaut.

- Dans la bibliothèque de plus de 300 exercices, cherchez et essayer ceux que je pratique actuellement :

    - Butterfly
    - Hamstring Rack Stretch
    - Hamstrings Stretch
    - Pigeon
    - Prayer Lat Stretch
    - Supine Piriformis Stretch
    - The Breakdancer
    - The Sagittarius
    - The Turtle
    - V Sit
    - Cobra To Prayer
    - Downward Facing Dog To Cobra
    - Standing Quad Stretch
    - Standing Forward Bend
    - Standing Hip Rotations
    - Calf Stretch On Wall
    - Squat To Stand
    - Cat And Cow

- Ajouter ceux que vous préférez à un protocole personnel

- Quand vous avez un peu de temps, même 5 minutes (et un peu éloigné des entraînements), lancez votre protocole en mode aléatoire, et faîtes autant d'exercices que votre emploi du temps le permet

- N'hésitez pas à me suggérer d'autres exercices


## Le principe de surcharge progressive {-}

Pour améliorer vos performances, il est nécessaire d'augmenter progressivement la charge d'entraînement. Cette progression ne doit pas être continue : on alterne généralement trois semaines d'augmentation avec une semaine allégée, dite semaine d'assimilation, pour permettre à l'organisme de récupérer et bénéficier de l'effet de surcompensation.

Cette charge peut être augmentée de trois façons principales : en jouant sur la fréquence (le nombre de séances par semaine), le volume (la durée ou la distance parcourue), ou l'intensité (la vitesse ou l'effort consenti).

**Cependant, il est important de ne pas augmenter ces trois facteurs en même temps**, et **cette augmentation doit rester raisonnable** (comme 10% par semaine et 50% sur une année).
Sinon, cela augmenterait considérablement le risque de surentraînement et de blessure.

L'augmentation progressive de la charge d'entraînement doit être raisonnée.
En général, il est conseillé de se concentrer sur **un seul facteur à la fois**.
L'ordre de priorité recommandé est le suivant :

1. **Fréquence** : Si vous faites moins de trois séances par semaine, commencez par augmenter le nombre de séances
avant d'augmenter la durée ou l'intensité. Ajouter une séance supplémentaire (comme une séance courte d'endurance fondamentale) permet de mieux répartir le volume et de favoriser la récupération active.

2. **Volume** : Une fois que vous avez stabilisé votre fréquence hebdomadaire, vous pouvez progressivement augmenter
la durée ou la distance totale de vos séances. Cela aide à développer l'endurance. Respectez la règle des 10 %,
c'est-à-dire n'augmentez pas le volume total de plus de 10 % par semaine (et 50% sur un an).

3. **Intensité** : Enfin, une fois que vous êtes à l'aise avec la fréquence et le volume, vous pouvez commencer
à ajouter ou augmenter des séances plus intenses (comme du fractionné ou des courses à allure spécifique).
Cependant, veillez à ce que les séances intensives restent bien espacées et que la récupération soit suffisante.

Ce principe de progressivité vaut aussi pour d'autres aspects :

- Dénivelé : trop de montées ou descentes techniques sans y être préparé.

- Changement brusque : nouveau type de terrain, nouvelles chaussures, changement de posture, etc.

Le corps s'adapte, mais a besoin de temps !
Un stress trop brutal crée des micro-lésions, puis des douleurs, et enfin des blessures.


## Gestion de la fatigue et prévention du surentraînement {-}

Il est crucial d'écouter son corps et de reconnaître les signes de fatigue.
Le surentraînement accroît drastiquement les risques de blessures, et peut aussi entraîner une diminution des performances.
Incorporez des semaines de récupération (par exemple, une semaine allégée après trois semaines intenses) et variez les intensités d'entraînement.

## Repos et récupération {-}

Le repos est tout aussi voire plus important que l'entraînement.
Il permet au corps de se réparer et de s'adapter aux efforts fournis.
Assurez-vous d'inclure des jours de repos actifs et des séances légères dans votre programme.

Après un effort intense, le corps subit une phase de fatigue. 
Mais, avec une récupération appropriée, il se renforce et s'adapte, menant à une amélioration des performances ; ce processus s'appelle la surcompensation.
Si le temps de récupération est trop court, le risque de blessures et de stagnation des performances augmente.
Les montres actuelles donnent une information sur le temps de récupération suggéré avant la prochaine séance intense.
Pour aller plus loin sur les temps de récupération, regardez [cette vidéo](https://www.youtube.com/watch?v=NTKeLwErKvQ).

Il existe plusieurs types de récupération :

- Sommeil : **Un bon sommeil est la base de toute bonne récupération !**

- Récupération passive : C'est le repos complet, sans activité physique.
Elle est essentielle après des séances d'entraînement intense ou des compétitions.
Le corps a besoin de ce temps pour réparer les tissus musculaires endommagés,
reconstituer les réserves de glycogène et réduire la fatigue.

- Récupération active : Cette méthode consiste à pratiquer une activité légère après un entraînement intense,
comme une promenade, du vélo à faible intensité ou de la natation.
La récupération active favorise la circulation sanguine,
aide à éliminer les déchets métaboliques, et réduit la raideur musculaire.

- Récupération nutritionnelle : Une alimentation adéquate est primordiale pour optimiser la récupération.
Après un entraînement, il est important de consommer des glucides pour reconstituer les réserves d'énergie,
ainsi que des protéines pour favoriser la réparation musculaire.
L'hydratation joue également un rôle clé dans la récupération,
car elle aide à réguler la température corporelle et à transporter les nutriments.
Et non, malheureusement la bière n'aide pas à récupérer physiquement, mais ça fait toujours du bien au moral.

- Récupération mentale: La récupération ne concerne pas seulement le corps, mais aussi l'esprit.
Prendre du temps pour se détendre, se reposer mentalement,
et pratiquer des activités relaxantes peut aider à réduire le stress
et à améliorer la concentration lors des prochaines séances d'entraînement.


## Motivation et mental {-}

La dimension mentale de la course est souvent aussi importante que l'entraînement physique.
Pour rester motivé, fixez-vous des objectifs clairs et atteignables, et célébrez vos petites victoires.
Entourez-vous d'autres coureurs et participez à des évènements pour renforcer votre motivation.
Acceptez que les progrès prennent du temps et que chaque course est une occasion d'apprendre et de s'améliorer.
